# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d9f55812e074b1b7f9d71c92b0cb91d1828fddea048207613f55f5d250dcc6dc7ba485bab5dc0072d389b45d562e0bbdc4b7c3ef408501f2ad096597336195

test:
  secret_key_base: 355441316eaa8f6e517ff20879330dfa2e666efa7edfbfbc5c8606b88ad3a4eff44f0b5e325953c4cf4152caa838414b964a9d2361c4520823e5f89827bd2bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
